version: '3'

services:
  webapp:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "./my.csf:/etc/my.cnf"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
    volumes:
      - "./hive.sql:/docker-entrypoint-initdb.d/1.sql"
    command: --default-authentication-plugin=mysql_native_password

#  jenkins:
#    image: jenkins/jenkins:lts-jdk17