version: '3'

services:
  webapp:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "./my.csf:/etc/my.cnf"
    networks:
      - app_network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3306:3306'
    volumes:
      - "./hive.sql:/docker-entrypoint-initdb.d/hive.sql"
      - my-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

  hiveai:
    build: ./hive-ai
    ports:
      - "5000:5000"
    environment:
        - FLASK_ENV=development
    command: python app.py

networks:
  app_network:
    driver: bridge
volumes:
  my-db:

