version: '3'

services:
  jenkins:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    environment:
      JENKINS_ADMIN_ID: root
      JENKINS_ADMIN_PASSWORD: root
      JENKIN_PORT: ${JENKINS_PORT}

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"  # SonarQube web interface
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - jenkins_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube_db

  sonarqube_db:
    image: postgres:12
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - jenkins_network

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

networks:
  jenkins_network:

#    e6ea5b9fa28e45c0b200876d19a37498